root = "."
tmp_dir = "tmp"

[build]
pre_cmd = [
  "npm run core:build",
  "npm run tailwind:build",
  "templ generate",
  "sqlc generate",
  "goose up",
]
exclude_dir = ["tmp", "node_modules", "gen", "spec", "static"]
exclude_file = ["views/*.go"]

[screen]
clear_on_rebuild = true
