root = "."
tmp_dir = "tmp"

[build]
pre_cmd = [
  "npm run core:build",
  "npm run tailwind:build",
  "templ generate",
  "sqlc generate",
  "goose up",
]
include_ext = ["go", "templ", "sql", "js", "css"]
exclude_dir = ["tmp", "node_modules", "gen", "spec", "public"]
exclude_regex = ["_templ.go"]

[screen]
clear_on_rebuild = true
